[project]
name = "chatty-commander"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openwakeword>=0.4.0",
    "pyautogui>=0.9.54",
    "pytest>=8.4.1",
    "requests>=2.32.4",
]

[dependency-groups]
dev = []
