[project]
name = "chatty-commander"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openwakeword>=0.4.0",
    "pyautogui>=0.9.54",
    "pytest>=8.4.1",
    "pytest-mock>=3.12.0",
    "pytest-cov>=4.1.0",
    "requests>=2.32.4",
    "argparse>=1.4.0", # Ensure argparse is available, though standard library
    "psutil>=7.0.0",
    "fastapi>=0.116.1",
    "uvicorn[standard]>=0.35.0",
    "python-jose[cryptography]>=3.5.0",
    "passlib[bcrypt]>=1.7.4",
    "python-multipart>=0.0.20",
    "pyjwt>=2.10.1",
    "bcrypt==4.0.1",
    "websockets>=15.0.1",
    "httpx>=0.28.1",
]

[project.scripts]
chatty = "cli:cli_main"

[dependency-groups]
dev = []

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
cache_dir = ".pytest_cache"
addopts = "--cov=. --cov-report=term --cov-report=html --cache-clear"

[tool.coverage.run]
source = [
    ".",
]
omit = [
    "tests/*",
    "archive/*",
    "webui/frontend/*",
    "*/__pycache__/*",
    "*/site-packages/*",
]

[tool.setuptools]
py-modules = ["cli", "command_executor", "command_extractor", "config", "config_cli", "helpers", "main", "model_manager", "state_manager"]
packages = ["utils"]

[tool.black]
line-length = 100
target-version = ["py311"]
include = "\\.pyi?$"
skip-string-normalization = true

[tool.ruff]
target-version = "py311"
line-length = 100
extend-exclude = ["webui/frontend", "node_modules", ".venv", "venv", "build", "dist", ".pytest_cache", "htmlcov"]
src = ["."]
fix = true

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "W",   # pycodestyle warnings
  "F",   # pyflakes
  "I",   # isort
  "B",   # bugbear
  "UP",  # pyupgrade
]
ignore = [
  "E203",  # whitespace before ':', compatible with Black
  "E266",  # too many leading '#' for block comment
  "E501",  # handled by Black
]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = false

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["chatty_commander"]
